#!/bin/bash

remote="origin"

while [[ $# -gt 0 ]]; do
    case $1 in
        --target)
            remote="$2"
            shift 2
            ;;
        *)
            shift
            ;;
    esac
done

read -p "Commit message: " msg

git add .
git commit -m "$msg"
git push "$remote" main
